shop/urls.py
from django.urls import path

from .views import DeliveryAndPaymentView, ExchangeAndReturnView, HowToUseView, \
    SupportView, ContactsView, AboutUsView, HomePageView

app_name = 'shop'


urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('delivery_and_payment/', DeliveryAndPaymentView.as_view(), name='delivery_and_payment_url'),
    path('exchange_and_return/', ExchangeAndReturnView.as_view(), name='exchange_and_return_url'),
    path('how_to_use/', HowToUseView.as_view(), name='how_to_use_url'),
    path('support/', SupportView.as_view(), name='support_url'),
    path('contacts/', ContactsView.as_view(), name='contacts_url'),
    path('about_us/', AboutUsView.as_view(), name='about_us_url')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">


<head>
    {% block meta_tags %}
    <meta charset="UTF-8">
    {% endblock meta_tags %}
    <title>
        {% block title %}{% endblock title %}
    </title>
    {% block stylesheets %}{% endblock stylesheets %}
    {% block extra_head %}

    <style>
        header  {
            display: block;
        }
    </style>

    {% endblock %}
</head>
<body>
{% block body %}

<header>
    {% block header %}
        {% block slider%}
        {% endblock slider %}
    {% endblock header %}

    {% block headerpopup %} {% endblock headerpopup %}
</header>
    {% block content %} {% endblock content %}

    {% block footer %} {% endblock footer %}

    {% block extra_javascript %} {% endblock extra_javascript %}

    {% block javascript %}{% endblock javascript %}
{% endblock body %}
</body>
</html>

templates/sidebar.html
{% load static %}

<aside class="sidebar">
    <a href="{% url 'shop:delivery_and_payment_url' %}">Доставка и оплата</a>
    <a href="{% url 'shop:exchange_and_return_url' %}">Обмен и возврат</a>
    <a href="{% url 'shop:how_to_use_url' %}">Как использовать</a>
    <a href="{% url 'shop:support_url' %}">Помощь</a>
    <a href="{% url 'shop:contacts_url' %}">Контакты</a>
    <a href="{% url 'shop:about_us_url' %}">О нас</a>
</aside>