orders/urls.py
from django.urls import path

from .views import OrderCreateView, OrderView

app_name='orders'

urlpatterns = [
    path('order/', OrderView.as_view(), name='order'),
    path('order_create/', OrderCreateView.as_view(), name='order_create'),
    # path('order_item/', OrderItemCreateView.as_view(), name='order_item'),
]

shop/urls.py
from django.urls import path

from .views import DeliveryAndPaymentView, ExchangeAndReturnView, HowToUseView, \
    SupportView, ContactsView, AboutUsView, HomePageView

app_name = 'shop'


urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('delivery_and_payment/', DeliveryAndPaymentView.as_view(), name='delivery_and_payment_url'),
    path('exchange_and_return/', ExchangeAndReturnView.as_view(), name='exchange_and_return_url'),
    path('how_to_use/', HowToUseView.as_view(), name='how_to_use_url'),
    path('support/', SupportView.as_view(), name='support_url'),
    path('contacts/', ContactsView.as_view(), name='contacts_url'),
    path('about_us/', AboutUsView.as_view(), name='about_us_url')
]

orders/models.py
from django.db import models
from catalog.models import TimeStampedModel, Product
from django.utils.translation import ugettext as _


class Order(TimeStampedModel):
    city = models.CharField(
        max_length=256,
        null=True, blank=True,
        verbose_name=_('Город покупателя')
    )
    first_name = models.CharField(
        max_length=256,
        verbose_name=_('Имя покупателя')
    )
    last_name = models.CharField(
        max_length=256,
        verbose_name=_('Фамилия покупателя'),
        null=True, blank=True
    )
    patronymic = models.CharField(
        max_length=256,
        verbose_name=_('Отчество'),
        null=True, blank=True,
    )
    email = models.EmailField(
        max_length=30,
        null=True, blank=True,
        verbose_name=_('Електронный адрес покупателя')
    )
    phone = models.CharField(
        max_length=13,
        verbose_name=_('Телефон покупателя')
    )
    nova_poshta = models.CharField(
        max_length=256,
        null=True, blank=True,
        verbose_name=_('Отделение новой почты')
    )

    class Meta:
        verbose_name = _('Заказ')
        verbose_name_plural = _('Заказы')

    @property
    def full_name(self):
        return '{} {} {}'.format(self.last_name, self.first_name, self.patronymic)

    def __str__(self):
        return self.full_name


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )
    quantity = models.PositiveSmallIntegerField(
        verbose_name=_('Количество товара'),
        default=1
    )

orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'city',
            'first_name',
            'last_name',
            'patronymic',
            'email',
            'phone',
            'nova_poshta',
        )

orders/views.py
from django.http import JsonResponse
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from basket.cart import Cart
from catalog.mixins import AjaxableResponseMixin
from .models import Order, OrderItem


class OrderView(TemplateView):
    template_name = 'orders/order.html'


class OrderCreateView(AjaxableResponseMixin, CreateView):
    # form_class = OrderForm
    model = Order
    fields = (
        'city',
        'first_name',
        'last_name',
        'patronymic',
        'email',
        'phone',
        'nova_poshta',
    )

    success_url = 'order/'

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.is_ajax():
            order = form.save()
            cart = Cart(self.request)
            OrderItem.objects.bulk_create([
                OrderItem(order=order, product=item['product'], quantity=item['quantity'])
                for item in cart
            ])
            return JsonResponse({
                'successed': True,
            })
        else:
            return response

templates/orders/order.html
{% extends 'shop/index.html' %}
{% load static %}
{% block slider %}
{% endblock slider %}
{% block content %}

<section class="">
    <div class="container">
        <div class="order-block">
            <form id="order_create_form" method="post" action="{% url 'orders:order_create' %}">
                {% csrf_token %}
                <div class="left">
                    <div class="checkout-block">
                        <h3>Оформить заказ</h3>
                        <div class="inputs">
                            <label for="">Ваш город</label>
                            <div>
                                <input name="city" type="text" required>
                            </div>
                        </div>

                        <div class="delivery">
                            <label for="">Доставка</label>
                            <div class="dell">
                                <div class="np-delivery">
                                    <span style="margin-left: 35px">Доставка Новой Почтой</span>
                                </div>
                            </div>
                        </div>

                        <div class="inputs">
                            <label for="">Телефон</label>
                            <div>
                                <input name="phone" type="tel" required>
                            </div>
                        </div>
                        <div class="inputs">
                            <label for="">Имя</label>
                            <div>
                                <input name="first_name" type="text" required>
                            </div>
                        </div>
                        <div class="inputs">
                            <label for="">Фамилия</label>
                            <div>
                                <input name="last_name" type="text" required>
                            </div>
                        </div>
                        <div class="inputs">
                            <label for="">Отчество</label>
                            <div>
                                <input name="patronymic" type="text" required>
                            </div>
                        </div>
                        <div class="inputs">
                            <label for="">E-mail</label>
                            <div>
                                <input name="email" type="email" required>
                            </div>
                        </div>
                    </div>
                    <div class="info-about-post">
                        <h4>Информация об отделении Новой Почты</h4>
                        <div class="inputs">
                            <label for="">Номер отделения</label>
                            <div>
                                <input name="nova_poshta" type="text" required>
                            </div>
                        </div>
                    </div>
                    <button class="order-btn hid">Оформить заказ </button>
                </div>
                <div class="order-cart-products">
                    {% for item in cart %}
                        <div class="cart-product-item">
                            <div class="cart-product-img">
                                <img src="{{ item.product.imageurls.first.url }}">
                            </div>
                            <div class="cart-product-info">
                                <h5 class="product-name">{{ item.product.name }}</h5>
                                <span class="product-code">Код: {{ item.product.vendor_code }}</span>

                                <div class="amountandprice">
                                    <div class="product-price">{{ item.product.price }} грн</div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}




                    <div class="order-total-price">
                        <p>Итого:</p>
                        <span class="total-price">{{ cart.get_total_price }} грн</span>
                    </div>
                    <button class="order-btn mob">Оформить заказ </button>
                </div>
            </form>
        </div>
    </div>
</section>


{% endblock content %}