catalog/urls.py
from django.urls import path
from .views import *

app_name = 'catalog'

urlpatterns = [
    path('products/', ProductListView.as_view(), name='products_list'),
    path('products/category/<int:category_id>', ProductListByCategoryView.as_view(), name='products_by_category'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
]

shop/urls.py
from django.urls import path

from .views import DeliveryAndPaymentView, ExchangeAndReturnView, HowToUseView, \
    SupportView, ContactsView, AboutUsView, HomePageView

app_name = 'shop'


urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('delivery_and_payment/', DeliveryAndPaymentView.as_view(), name='delivery_and_payment_url'),
    path('exchange_and_return/', ExchangeAndReturnView.as_view(), name='exchange_and_return_url'),
    path('how_to_use/', HowToUseView.as_view(), name='how_to_use_url'),
    path('support/', SupportView.as_view(), name='support_url'),
    path('contacts/', ContactsView.as_view(), name='contacts_url'),
    path('about_us/', AboutUsView.as_view(), name='about_us_url')
]

catalog/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.translation import ugettext as _
from catalog import constants


class CatalogManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        ids = Product.objects.all().values_list('category_id', flat=True)
        queryset = super().get_queryset().filter(id__in=ids).get_ancestors(include_self=True)
        return queryset


class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('Дата создания'))
    updated = models.DateTimeField(auto_now=True, verbose_name=_('Дата обновления'))

    class Meta:
        abstract = True


class Category(MPTTModel):
    id = models.PositiveIntegerField(
        primary_key=True,
        verbose_name='id - primary key',
    )
    name = models.CharField(
        max_length=256,
        verbose_name=_('Название категории'),
    )
    parent = TreeForeignKey(
        'self',
        null=True,
        blank=True,
        related_name='children',
        on_delete=models.SET_NULL,
        db_index=True,
    )
    # objects = CatalogManager()
    category_by_products = CatalogManager()

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = _('Категория')
        verbose_name_plural = _('Категории')

    @property
    def get_category_level(self):
        return self.get_level()

    def __str__(self):
        return '{}'.format(self.name)


class Product(TimeStampedModel):
    """
    Если поле contractor=NULL - товар добавлен поставщиком.
    В противном случае это товар, добавленный партнером от поставщика
    """

    id = models.PositiveIntegerField(
        primary_key=True,
        verbose_name='id - primary key',
    )

    category = TreeForeignKey(
        Category,
        null=True, blank=True,
        verbose_name=_('Категория товара'),
        on_delete=models.SET_NULL,
    )

    availability = models.CharField(
        max_length=13,
        verbose_name=_('Доступность товара'),
        choices=constants.PRODUCT_AVAILABILITY,
        default='IN_STOCK'
    )
    name = models.CharField(
        max_length=255,
        verbose_name=_('Имя продукта')
    )
    vendor_code = models.CharField(
        max_length=63,
        verbose_name=_('Артикул'),
    )
    product_type = models.CharField(
        max_length=256,
        verbose_name=_('Вид товара')
    )
    brand = models.CharField(
        max_length=255,
        verbose_name=_('Бренд'),
    )
    count = models.PositiveIntegerField(
        default=0,
        verbose_name=_('Наличие'),
    )
    description = models.TextField(
        max_length=4095,
        null=True, blank=True,
        verbose_name=_('Описание'),
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True, blank=True,
        verbose_name=_('Цена товара'),
    )

    is_best = models.BooleanField(
        default=False,
        verbose_name=_('Лучший товар')
    )
    is_recommended = models.BooleanField(
        default=False,
        verbose_name=_('Рекомендуемые товары')
    )

    def __str__(self):
        return '{0}'.format(self.name)

    class Meta:
        verbose_name = _('Товар')
        verbose_name_plural = _('Товары')


class ProductImageURL(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='imageurls'
    )
    url = models.URLField(
        verbose_name=_('Ссылка на картинку'),
    )


class ProductCharacteristic(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, on_delete=models.CASCADE,
                                related_name='characteristics')
    characteristic_type = models.CharField(
        max_length=255,
        blank=True, null=True,
        verbose_name=_('Тип характеристики'),
    )
    name = models.CharField(
        max_length=255,
        null=True, blank=True,
        verbose_name=_('Имя характеристики'),
    )
    value = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f'{self.characteristic_type} -- {self.name} -- {self.value}'

    class Meta:
        ordering = ['product']
        verbose_name = _('Характеристика')
        verbose_name_plural = _('Характеристики продукта')
        unique_together = ['product', 'characteristic_type', 'name', 'value']


class FeedBack(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='product_feedback'
    )
    name = models.CharField(
        max_length=255,
        blank=True, null=True,
        verbose_name=_('Имя пользователя'),
    )
    content = models.TextField(verbose_name=_('Отзыв'), max_length=1024)
    pub_date = models.DateTimeField(
        verbose_name=_('Дата создания отзыва'),
        auto_now_add=True
    )
    reply = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True, blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = _('Отзыв')
        verbose_name_plural = _('Отзывы')

    def __str__(self):
        return self.content[0:200]

catalog/views.py
from django.views.generic import ListView, DetailView
from catalog.models import Product, ProductCharacteristic
from catalog.mixins import ProductFilterMixin


class ProductListView(ProductFilterMixin, ListView):
    model = Product
    paginate_by = 15
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'


class ProductListByCategoryView(ProductFilterMixin, ListView):
    model = Product
    paginate_by = 15
    template_name = 'catalog/product_list_by_category.html'
    context_object_name = 'products'

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id', None)
        queryset = queryset.filter(category_id=category_id)
        return queryset


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_characteristics'] = ProductCharacteristic.objects.filter(
            product_id=self.kwargs['pk']).order_by('characteristic_type')
        return context

templates/catalog/product.html
{% extends 'shop/index.html' %}
{% load static %}
{% block slider %}
{% endblock slider %}
{% block content %}

<section class="">
    <div class="container">
        <div class="product-block">
            <div class="product-slider">
                <div class="slider slider-nav">
                    {% for image in product.imageurls.all %}
                    <div class="mini-img">
                        <img src="{{ image.url }}" alt="">
                    </div>
                    {% endfor %}
                </div>

                <div class="slider slider-for">
                    {% for image in product.imageurls.all %}
                    <div class="mini-img">
                        <img src="{{ image.url }}" alt="">
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="product-info">
                <div class="product-title">
                    <h5 class="product-name">{{ product.name }}</h5>
                    <span class="code">Код: {{ product.vendor_code }}</span>
                </div>
                <div class="seller">
                    <h6>Продавец этого товара Rozetka</h6>
                    <div class="brand">
                        <img src="{% static  'app/img/rozetka.png'%}">
                    </div>
                </div>
{#                <div class="product-color">#}
{#                    <h5>Цвет</h5>#}
{#                    <select>#}
{#                        <option>Черный</option>#}
{#                        <option>Белый</option>#}
{#                    </select>#}
{#                </div>#}
                <div class="price-block">
{#                    <span class="old-price">{{ product.price }}</span>#}
                    <span class="price">{{ product.price }}</span>
                </div>
                <div class="btns">
                    <button onclick="add_to_cart({{product.id}}, 1)" class="buy">Купить</button>
                    <button class="wish"><img src="{% static 'app/img/whish-btn.png' %}" alt=""></button>
                </div>
            </div>
        </div>
        <div class="about-product">
            <div class="characteristics">
                <h4>Характеристики товара</h4>
                {% regroup product.characteristics.all by characteristic_type as characteristic_type_list %}
                {% for characteristic_type in characteristic_type_list %}
                    <h6>{{characteristic_type.grouper}}</h6>
                    <ul class="characteristics-list">
                        {% for characteristic in characteristic_type.list %}
                            <li> {{ characteristic.name }}   <span>{{ characteristic.value }}</span></li>
                        {% endfor %}
                    </ul>
                {% endfor %}
            </div>
            <div class="description">
                <h4>Описание</h4>
                <p>{{ product.description }}</p>
            </div>
        </div>
        <div class="reviews-block">
            {% if product.product_feedback.all %}
            <h3>Отзывы о {{ product.name }}</h3>
            {% for feedback in product.product_feedback.all %}
            <div class="review">
                <div>
                    <h5 class="user-name">{{ feedback.name }}</h5>
                </div>
                <div class="review-text">
                    <p>{{ feedback.content }}</p>
                    <div class="review-actions">
{#                        <span class="reply"><img src="{% static 'app/img/chat.svg' %}" alt="">Ответить</span>#}
{#                        <span><a href="#" class="useful">Полезен ли отзыв?</a></span>#}
{#                        <button class="like"><img src="img/like.svg" alt=""><span>(10)</span></button>#}
{#                        <button class="dislike"><img src="img/dislike.svg" alt=""><span>(3)</span></button>#}
                    </div>
                </div>
                <div class="date">{{ feedback.pub_date }}</div>
            </div>
            {% endfor %}
        {% endif %}
        </div>
    </div>
</section>

{% endblock content %}

templates/catalog/product_list.html
{% extends 'shop/index.html' %}
{% load static %}
{% block slider %}
{% endblock %}
{% block content %}

<section class="about">
    <div class="container">
        <main class="products-product-wrap">
            <aside class="filter">
                <form method="get" action="{% url 'catalog:products_list'  %}">
                    <div class="filter-price">
                        <h5>Цена</h5>
                        <div class="filter-price-row">
                            <span>от</span>
                            <input name="min_price" type="number" value="{{ min_price }}">
                            <span>до</span>
                            <input name="max_price" type="number" value="{{ max_price }}">
                            <span>грн</span>
                        </div>
                    </div>
                    <div class="filter-brand">
                        <h5>Бренд</h5>
                        {% for brand in brand_list %}
                            {% if brand in brands %}
                                <p><input name="brand" type="checkbox" value="{{ brand }}" checked>{{ brand }}</p>
                            {% else %}
                                <p><input name="brand" type="checkbox" value="{{ brand }}">{{ brand }}</p>
                            {% endif %}
                        {% endfor %}
                    </div>
                <button  class="button-by-items">Сортировать</button>
                </form>
            </aside>
            <div class="products-list">
                {% for product in products %}
                <div class="product">
                    <a href="{% url 'catalog:product_detail' product.pk %}">
                        <div class="product-img">
                            <img src="{{ product.imageurls.first.url }}" alt="">
                        </div>
                        <h5 class="product-title">{{ product.name }}</h5>
                        <div class="product-price">{{ product.price }}</div>
{#                        <div class="product-old-price">29 000 ₴</div>#}
                        <div class="wish-btn"><img src="{% static 'app/img/whish-btn.png' %}" alt=""></div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </main>
        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number }}{{ join_brand }}{{ min_price_join }}{{ max_price }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}{{ join_brand }}{{ min_price_join }}{{ max_price_join }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}{{ join_brand }}{{ min_price_join }}{{ max_price_join }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}
    </div>
</section>

{% endblock content %}

templates/catalog/product_list_by_category.html
{% extends 'shop/index.html' %}
{% load static %}
{% block slider %}
{% endblock %}
{% block content %}

<section class="about">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="#">Интернет-магазин</a></li>
            <li><a href="#">Техника</a></li>
            <li>Ноутбуки</li>
        </ul>
    </div>
    <div class="container">
        <main class="products-product-wrap">
            <aside class="filter">
                <form method="get" action="{% url 'catalog:products_list' %}">
                    <div class="filter-price">
                        <h5>Цена</h5>
                        <div class="filter-price-row">
                            <span>от</span>
                            <input name="min_price" type="number" value="{{ min_price }}">
                            <span>до</span>
                            <input name="max_price" type="number" value="{{ max_price }}">
                            <span>грн</span>
                        </div>
                    </div>
                    <div class="filter-brand">
                        <h5>Бренд</h5>
                        {% for brand in brand_list %}
                            {% if brand in brands %}
                                <p><input name="brand" type="checkbox" value="{{ brand }}" checked>{{ brand }}</p>
                            {% else %}
                                <p><input name="brand" type="checkbox" value="{{ brand }}">{{ brand }}</p>
                            {% endif %}
                        {% endfor %}
                    </div>
                <button  class="button-by-items">Сортировать</button>
                </form>
            </aside>
            <div class="products-list">
                {% for product in products %}
                <div class="product">
                    <a href="#">
                        <div class="product-img">
                            <img src="{{ product.imageurls.first.url }}" alt="">
                        </div>
                        <h5 class="product-title">{{ product.name }}</h5>
                        <div class="product-price">{{ product.price }}</div>
{#                        <div class="product-old-price">29 000 ₴</div>#}
                        <div class="wish-btn"><img src="{% static 'app/img/whish-btn.png' %}" alt=""></div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </main>
        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number }}{{ join_brand }}{{ min_price_join }}{{ max_price }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}{{ join_brand }}{{ min_price_join }}{{ max_price_join }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}{{ join_brand }}{{ min_price_join }}{{ max_price_join }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}
    </div>
</section>

{% endblock content %}